dat1 = read.delim("D:/github_stuff/Plant-FATE_patch/muh.txt")

par(mfrow=c(3,3), mar=c(4,4,1,1), oma=c(1,1,1,1))
plot(dat1$swp, ylab="SWP", xlab="Year", type="l", lwd=2)
#plot(dat1$h, ylab="hydraulics", xlab="Year", type="l", lwd=2)
plot(dat1$mu, ylab="Mortality", xlab="Year", col="brown", type="l", lwd=2)

dat = read.delim("D:/github_stuff/Plant-FATE_patch/assim.txt")
plot(y=dat$fecundity_mort,x=dat$i, ylab="fec_mort", xlab="Year", type="l", lwd=2)
plot(y=dat$fecundity,x=dat$i, ylab="fec", xlab="Year", type="l", lwd=2)
plot(y=exp(-dat$mortality),x=dat$i, ylab="mort_cumul", xlab="Year", type="l", lwd=2)
plot(y=dat$mortality_inst,x=dat$i, ylab="mort_inst", xlab="Year", type="l", lwd=2)
plot(y=dat$germinated,x=dat$i, ylab="germ", xlab="Year", type="l", lwd=2)
plot(y=dat$height,x=dat$i, ylab="height", xlab="Year", type="l", lwd=2)
plot(y=dat$diameter,x=dat$i, ylab="diameter", xlab="Year", type="l", lwd=2)
#plot(diff((dat$fecundity_mort[50:150])))
